// apps/www/app/components/Wysiwyg/BubbleMenu/index.tsx
﻿import { BubbleMenu as TipTapBubbleMenu } from '@tiptap/react';
import { Editor } from '@tiptap/react';
import { FC } from 'react';

import { IconBold } from '~/assets/icons/Bold';
import { IconHighLighter } from '~/assets/icons/HighLighter';
import { IconItalic } from '~/assets/icons/Italic';
import { IconLink } from '~/assets/icons/Link';
import { IconStrikethrough } from '~/assets/icons/Strikethrough';
import { IconUnlink } from '~/assets/icons/Unlink';

import { MenuButton } from './MenuButton';
import { containerStyle } from './style.css';

type Props = {
  editor: Editor;
};

export const BubbleMenu: FC<Props> = ({ editor }) => {
  const setLink = () => {
    if (!editor) return;
    if (typeof window !== 'undefined') {
      const url = window.prompt('URL') || '';
      editor
        .chain()
        .focus()
        .extendMarkRange('link')
        .setLink({ href: url })
        .run();
    }
  };

  return (
    <TipTapBubbleMenu editor={editor} className={containerStyle}>
      <MenuButton
        onClick={() => editor.chain().focus().toggleBold().run()}
        isActive={editor.isActive('bold')}
      >
        <IconBold />
      </MenuButton>
      <MenuButton
        onClick={() => editor.chain().focus().toggleItalic().run()}
        isActive={editor.isActive('italic')}
      >
        <IconItalic />
      </MenuButton>
      <MenuButton
        onClick={() => editor.chain().focus().toggleHighlight().run()}
        isActive={editor.isActive('highlight')}
      >
        <IconHighLighter />
      </MenuButton>
      <MenuButton
        onClick={() => editor.chain().focus().toggleStrike().run()}
        isActive={editor.isActive('strike')}
      >
        <IconStrikethrough />
      </MenuButton>
      {editor.isActive('link') && (
        <MenuButton
          onClick={() => editor.chain().focus().unsetLink().run()}
          isActive={false}
        >
          <IconUnlink />
        </MenuButton>
      )}
      {!editor.isActive('link') && (
        <MenuButton onClick={setLink} isActive={false}>
          <IconLink />
        </MenuButton>
      )}
    </TipTapBubbleMenu>
  );
};

// hosting/components/molecules/BubbleMenu.vue
﻿<template>
  <bubble-menu v-if="editor" :editor="editor" class="bubblemenu">
    <button
      :class="{ 'is-active': editor.isActive('bold') }"
      @click="editor.chain().focus().toggleBold().run()"
    >
      <fa-icon icon="bold" />
    </button>
    <button
      :class="{ 'is-active': editor.isActive('italic') }"
      @click="editor.chain().focus().toggleItalic().run()"
    >
      <fa-icon icon="italic" />
    </button>
    <button
      :class="{ 'is-active': editor.isActive('highlight') }"
      @click="editor.chain().focus().toggleHighlight().run()"
    >
      <fa-icon icon="highlighter" />
    </button>
    <button
      :class="{ 'is-active': editor.isActive('strike') }"
      @click="editor.chain().focus().toggleStrike().run()"
    >
      <fa-icon icon="strikethrough" />
    </button>
    <button
      v-if="editor.isActive('link')"
      @click="editor.chain().focus().unsetLink().run()"
    >
      <fa-icon icon="unlink" />
    </button>
    <button
      v-else
      :class="{ 'is-active': editor.isActive('link') }"
      @click="setLink"
    >
      <fa-icon icon="link" />
    </button>
  </bubble-menu>
</template>
<script lang="ts">
import Vue from 'vue'
import { BubbleMenu } from '@tiptap/vue-2'
export default Vue.extend({
  components: {
    BubbleMenu,
  },
  props: {
    editor: {
      type: Object,
      default: () => {},
    },
  },
  methods: {
    setLink() {
      if (process.client) {
        const url = window.prompt('URL')
        this.editor
          .chain()
          .focus()
          .extendMarkRange('link')
          .setLink({ href: url })
          .run()
      }
    },
  },
})
</script>
<style lang="scss" scoped>
.bubblemenu {
  background: $white;
  border: 1px solid $gray-black;
  border-radius: 5px;
  padding: .3rem .4rem;
  button {
    display: -webkit-inline-box;
    display: -ms-inline-flexbox;
    display: inline-flex;
    background: transparent;
    border: 0;
    color: $black;
    padding: 4px 6px;
    border-radius: 3px;
    cursor: pointer;

    &:last-child {
      margin-right:0;
    }
    &:hover {
      background-color: $yellow;
    }
    &.is-active {
      background-color:hsla(0,0%,100%,.2);
    }
  }
}
</style>
