// apps/www/app/components/Wysiwyg/BubbleMenu/index.tsx
﻿import { BubbleMenu as TipTapBubbleMenu } from '@tiptap/react';
import { Editor } from '@tiptap/react';
import { FC } from 'react';

import { IconBold } from '~/assets/icons/Bold';
import { IconHighLighter } from '~/assets/icons/HighLighter';
import { IconItalic } from '~/assets/icons/Italic';
import { IconLink } from '~/assets/icons/Link';
import { IconStrikethrough } from '~/assets/icons/Strikethrough';
import { IconUnlink } from '~/assets/icons/Unlink';

import { MenuButton } from './MenuButton';
import { containerStyle } from './style.css';

type Props = {
  editor: Editor;
};

export const BubbleMenu: FC<Props> = ({ editor }) => {
  const setLink = () => {
    if (!editor) return;
    if (typeof window !== 'undefined') {
      const url = window.prompt('URL') || '';
      editor
        .chain()
        .focus()
        .extendMarkRange('link')
        .setLink({ href: url })
        .run();
    }
  };

  return (
    <TipTapBubbleMenu editor={editor} className={containerStyle}>
      <MenuButton
        onClick={() => editor.chain().focus().toggleBold().run()}
        isActive={editor.isActive('bold')}
      >
        <IconBold />
      </MenuButton>
      <MenuButton
        onClick={() => editor.chain().focus().toggleItalic().run()}
        isActive={editor.isActive('italic')}
      >
        <IconItalic />
      </MenuButton>
      <MenuButton
        onClick={() => editor.chain().focus().toggleHighlight().run()}
        isActive={editor.isActive('highlight')}
      >
        <IconHighLighter />
      </MenuButton>
      <MenuButton
        onClick={() => editor.chain().focus().toggleStrike().run()}
        isActive={editor.isActive('strike')}
      >
        <IconStrikethrough />
      </MenuButton>
      {editor.isActive('link') && (
        <MenuButton
          onClick={() => editor.chain().focus().unsetLink().run()}
          isActive={false}
        >
          <IconUnlink />
        </MenuButton>
      )}
      {!editor.isActive('link') && (
        <MenuButton onClick={setLink} isActive={false}>
          <IconLink />
        </MenuButton>
      )}
    </TipTapBubbleMenu>
  );
};

// www/components/form/BubbleMenu.vue
﻿<template>
  <bubble-menu v-if="props.editor" :editor="props.editor" class="bubblemenu">
    <button :class="{ 'is-active': props.editor.isActive('bold') }"
      @click="props.editor.chain().focus().toggleBold().run()">
      <IconBold />
    </button>
    <button :class="{ 'is-active': props.editor.isActive('italic') }"
      @click="props.editor.chain().focus().toggleItalic().run()">
      <IconItalic />
    </button>
    <button :class="{ 'is-active': props.editor.isActive('highlight') }"
      @click="props.editor.chain().focus().toggleHighlight().run()">
      <IconHighLighter />
    </button>
    <button :class="{ 'is-active': props.editor.isActive('strike') }"
      @click="props.editor.chain().focus().toggleStrike().run()">
      <IconStrikethrough />
    </button>
    <button v-if="props.editor.isActive('link')" @click="props.editor.chain().focus().unsetLink().run()">
      <IconUnlink />
    </button>
    <button v-else :class="{ 'is-active': props.editor.isActive('link') }" @click="setLink">
      <IconLink />
    </button>
  </bubble-menu>
</template>
<script lang="ts" setup>
import { Editor, BubbleMenu } from '@tiptap/vue-3';

const props = defineProps<{
  editor: Editor;
}>();

const setLink = () => {
  if (!props.editor) return;
  if (process.client) {
    const url = window.prompt('URL') || '';
    props.editor
      .chain()
      .focus()
      .extendMarkRange('link')
      .setLink({ href: url })
      .run()
  }
};
</script>
<style lang="scss" scoped>
.bubblemenu {
  background: $white;
  border: 1px solid $gray-black;
  border-radius: 5px;
  padding: .3rem .4rem;

  button {
    display: -webkit-inline-box;
    display: -ms-inline-flexbox;
    display: inline-flex;
    background: transparent;
    border: 0;
    color: $black;
    padding: 4px 6px;
    border-radius: 3px;
    cursor: pointer;

    &:last-child {
      margin-right: 0;
    }

    &:hover {
      background-color: $yellow;
    }

    &.is-active {
      background-color: hsla(0, 0%, 100%, .2);
    }
  }
}
</style>
