// apps/www/app/components/Wysiwyg/index.tsx
﻿import { useDropZone } from '@reactuses/core';
import FloatingMenu from '@tiptap/extension-floating-menu';
import Highlight from '@tiptap/extension-highlight';
import Image from '@tiptap/extension-image';
import Link from '@tiptap/extension-link';
import { useEditor, EditorContent, AnyExtension } from '@tiptap/react';
import StarterKit from '@tiptap/starter-kit';
import { ComponentPropsWithRef, FC, useRef, useState } from 'react';

import { ImageUploader } from '~/components/ImageUploader';
import { articleStyle } from '~/styles/article.css';
import { zIndex } from '~/utils/style';

import { BubbleMenu } from './BubbleMenu';
import { FloatingMenu as FloatingMenuComponent } from './FloatingMenu';
import { containerStyle, modalStyle } from './style.css';

type Props = ComponentPropsWithRef<'textarea'> & {
  content: string;
  uploadpath: string;
  onUpdate: (content: string) => void;
};

export const Wysiwyg: FC<Props> = ({ content, uploadpath, onUpdate }) => {
  const className = [articleStyle, containerStyle].join(' ');
  const dzRef = useRef(null);

  const [showImageUploader, setShowImageUploader] = useState<boolean>(false);

  const extensions: AnyExtension[] = [
    StarterKit,
    Image,
    Link,
    Highlight,
    FloatingMenu.configure({
      tippyOptions: {
        maxWidth: 'none',
        zIndex: zIndex('COVER'),
      },
      shouldShow: ({ editor, view, state, oldState }) => {
        console.log('Editor!', view, state, oldState);
        return editor.isActive('paragraph');
      },
    }),
  ];

  const editor = useEditor({
    extensions,
    content,
    onUpdate: ({ editor }) => {
      onUpdate(editor.getHTML());
    },
  });

  const isOverDropZone = useDropZone(dzRef, (files) => {
    console.log('files', files);
  });

  // editor.value = new Editor({
  //   content,
  //   extensions: [
  //     StarterKit,
  //     // // Caption,
  //     // Highlight,
  //     // // Subscript,
  //     // // TextStyle,
  //     // Image.configure({
  //     //   inline: false,
  //     // }),
  //     // Link.configure({
  //     //   openOnClick: false,
  //     // }),
  //     // // Placeholder.configure({
  //     // //   placeholder: 'ここに本文を書いていきましょう',
  //     // // }),
  //     // BubbleMenu.configure({
  //     //   shouldShow: ({ editor }) => {
  //     //     return !editor.isActive('image');
  //     //   },
  //     // }),
  //     // FloatingMenu.configure({
  //     //   // shouldShow: ({ editor, view, state, oldState }) => {
  //     //   //   console.log('Editor!', view, state, oldState)
  //     //   //   return editor.isActive('paragraph')
  //     //   // },
  //     // }),
  //     // Item.configure({
  //     //   HTMLAttributes: {
  //     //     class: 'mention',
  //     //   },
  //     //   suggestion: ItemSuggestion,
  //     // }),
  //   ],
  //   // onUpdate: () => {
  //   //   if (!editor.value) return;
  //   //   emit('update:modelValue', editor.value.getHTML());
  //   // },
  // });

  if (!editor) return;

  return (
    <div ref={dzRef}>
      <EditorContent editor={editor} className={className} />
      <FloatingMenuComponent
        editor={editor}
        showImageUploader={setShowImageUploader}
      />
      <BubbleMenu editor={editor} />
      {(showImageUploader || isOverDropZone) && (
        <div className={modalStyle}>
          <ImageUploader
            editor={editor}
            uploadpath={uploadpath}
            onClose={() => setShowImageUploader(false)}
          />
        </div>
      )}
    </div>
  );
};

// www/components/form/Wysiwyg.vue
﻿<template>
  <div v-if="editor" @click="editor && editor.commands.focus()" class="wrapper">
    <OrganismImageUploader :editor="editor" :show="showUploader" :on-close="closeImageUploader" />
    <div class="editor">
      <FormBubbleMenu :editor="editor" />
      <FormFloatingMenu :editor="editor" @showImageUploader="showImageUploader()" />
      <div class="inner">
        <editor-content :editor="editor" />
      </div>
    </div>
  </div>
</template>
<script lang="ts" setup>
import { Editor, EditorContent } from '@tiptap/vue-3';
import { StarterKit } from '@tiptap/starter-kit';

// import Subscript from '@tiptap/extension-subscript'
import { Highlight } from '@tiptap/extension-highlight';
// import TextStyle from '@tiptap/extension-text-style'
import { Link } from '@tiptap/extension-link';
import { Image } from '@tiptap/extension-image';
import { BubbleMenu } from '@tiptap/extension-bubble-menu';
import { FloatingMenu } from '@tiptap/extension-floating-menu';
import { Mention } from '@tiptap/extension-mention';
import { useTagSuggestion } from '~~/composables/suggestion/useTagSuggestion';
// import Placeholder from '@tiptap/extension-placeholder'

import Caption from '~~/utils/editor/Caption';
// import Item from '~/plugins/editor/Item'
// import ItemSuggestion from '~/plugins/suggestions/item'

const emit = defineEmits(['update:modelValue']);

const props = defineProps<{
  placeholder?: string
  modelValue: string
}>();

const editor = ref<Editor>();
// const image = ref<File>();
const showUploader = ref(false);

const { suggestion } = useTagSuggestion();

onMounted(() => {
  editor.value = new Editor({
    content: props.modelValue,
    extensions: [
      StarterKit,
      Caption,
      Highlight,
      // Subscript,
      // TextStyle,
      Image.configure({
        inline: false,
      }),
      Link.configure({
        openOnClick: false,
      }),
      // Placeholder.configure({
      //   placeholder: 'ここに本文を書いていきましょう',
      // }),
      BubbleMenu.configure({
        shouldShow: ({ editor }) => {
          return !editor.isActive('image');
        },
      }),
      FloatingMenu.configure({
        // shouldShow: ({ editor, view, state, oldState }) => {
        //   console.log('Editor!', view, state, oldState)
        //   return editor.isActive('paragraph')
        // },
      }),
      Mention.configure({
        HTMLAttributes: {
          class: 'mention',
        },
        suggestion,
      }),
    ],
    onUpdate: () => {
      if (!editor.value) return;
      emit('update:modelValue', editor.value.getHTML());
    },
  });
});

onUnmounted(() => editor.value?.destroy());

const showImageUploader = (): void => {
  showUploader.value = true;
};
const closeImageUploader = (): void => {
  showUploader.value = false;
};
</script>
<style lang="scss" scoped>
.editor {
  min-height: 25vh;
  position: relative;

  >.inner {
    width: 100%;
    height: 100%;
  }
}

.wrapper {
  height: 100%;
  cursor: text;
}

// .expanded {
//   width: 100%;
//   height: 100%;
// }

// .uploader {
//   padding: $gap;
// }

// .console {
//   margin-bottom: 10px;
// }
</style>
