// www/components/organism/ImageUploader.vue
﻿<template>
  <BlockModal v-if="show" :on-close="props.onClose">
    <div class="uploader">
      <div class="inner">
        <div v-show="file?.url" class="preview columns">
          <div class="image column c60">
            <img :src="file?.url" />
            <div class="close">
              <AtomButton class="button" :no-border="true" @click="removeImage">
                <IconClose />
              </AtomButton>
            </div>
          </div>
          <div class="data column c40">
            <div class="console">
              <AtomButton class="button expanded centered" :is-loading="isUploading" @click="uploadImage()">
                <IconUpload />
                アップロード
              </AtomButton>
            </div>
            <dl class="filedata">
              <dt>ファイルサイズ：</dt>
              <dd>{{ file?.file.size }}</dd>
              <dt>ファイルタイプ：</dt>
              <dd>{{ file?.file.type }}</dd>
              <dt>ファイル名：</dt>
              <dd>{{ file?.file.name }}</dd>
            </dl>
          </div>
        </div>
        <div v-show="!file?.url" class="drop" :class="{ 'is-over': isOverDropZone }">
          <div ref="dzRef" class="zone">
            <div class="inner" @click="() => openFileDialog()">
              <p class="uploadicon">
                <IconUpload />
              </p>
              <p class="caption">{{ dropCaption }}</p>
            </div>
          </div>
          <IconClose @click="props.onClose" class="trigger-close" />
        </div>
      </div>
    </div>
  </BlockModal>
</template>
<script lang="ts" setup>
import dayjs from 'dayjs';
import { getStorage, uploadBytes, getDownloadURL, ref as storageRef } from 'firebase/storage';
import { Editor } from '@tiptap/vue-3';
import { useDropZone, useFileDialog } from '@vueuse/core';
import { ResizedImage, resizeImage } from '~~/utils/image';
import { getExt } from '~/utils/file';
import { useFirebase } from '~~/composables/firebase/useFirebase';

type Props = {
  editor: Editor;
  show: boolean;
  onClose: () => void;
  onChange?: (file: string) => void;
  defaultImage?: string;
}

const props = withDefaults(
  defineProps<Props>(),
  {
    onChange: () => {},
    defaultImage: '',
  }
);

const { fb } = useFirebase();
const storage = getStorage(fb);
const dzRef = ref<HTMLDivElement>();
const file = ref<ResizedImage>();
const isResizing = ref(false);
const isUploading = ref(false);

const { files, open: openFileDialog } = useFileDialog({
  multiple: false,
});

const dropCaption = computed(() => {
  if (isOverDropZone.value) return '画像ファイルをアップロードできます';
  if (isResizing.value) return '画像をリサイズしています';
  return '画像ファイルをドロップしてください';
});

const onDrop = async (files: File[] | null) => {
  if (!files) return;

  try {
    isResizing.value = true;
    const originalFile = files[0];

    const resizedImage = await resizeImage(originalFile, {
      width: 1800,
      height: 1800,
    });

    if (!resizedImage) return;

    file.value = resizedImage;
  } catch (e) {
    console.error(e);
  }
  isResizing.value = false;
}

const { isOverDropZone } = useDropZone(dzRef, onDrop);

const uploadImage = async () => {
  if (!props.editor || !file.value) return;
  console.log('file.value', file.value);

  const ext = getExt(file.value.file);
  if (!ext) return;

  try {
    isUploading.value = true;
    const now = dayjs();

    const filename = `posts/${now.format('YYYY/MM')}/${now.unix()}.${ext}`;
    const uploadHandler = storageRef(storage, filename);

    await uploadBytes(uploadHandler, file.value.file);
    const url = await getDownloadURL(uploadHandler);

    props.editor.chain().focus().setImage({ src: url }).run();
    file.value = undefined;
  } catch (e) {
    console.error(e);
  }

  props.onClose();
  isUploading.value = false;
};

watch(files, () => {
  if (!files.value) return;
  onDrop([files.value[0]]);
});

const removeImage = () => {
  file.value = undefined;
};

</script>
<style lang="scss" scoped>
.uploader {
  padding: 15px;
  height: 100%;

  >.inner {
    padding: 10px;
    height: 100%;
    border: 1px solid $gray-black;
  }

  .drop {
    height: inherit;
    width: 100%;
    color: $gray-black;

    &.is-over {
      background: $yellow;
      color: $black;
    }

    .zone {
      width: 100%;
      height: inherit;
      display: flex;
      align-items: center;
      justify-content: center;

      >.inner {
        position: relative;

        >.uploadicon {
          width: 80px;
          margin: auto;
          margin-bottom: 20px;
          cursor: pointer;

          >.icon {
            width: 80px;
            height: 80px;
            display: block;
          }
        }

        >.caption {
          min-width: 240px;
          font-size: 0.9rem;
          text-align: center;
        }
      }
    }

    .trigger-close {
      position: absolute;
      top: 35px;
      left: 35px;
      cursor: pointer;

      &:hover {
        color: $yellow;
      }
    }
  }

  .preview {
    width: 100%;
    height: 100%;
    display: flex;

    >.image {
      // width: 100%;
      height: 100%;
      position: relative;
      background-color: $gray-black;
      display: flex;
      align-items: center;
      justify-content: center;

      img {
        max-width: 100%;
        max-height: 100%;
      }

      >.close {
        width: 100%;
        height: 100%;
        position: absolute;
        top: 0;
        left: 0;
        align-items: center;
        justify-content: center;
        background-color: $white-transparent-60;
        display: none;
      }

      &:hover {
        >.close {
          display: block;
          width: 100%;
          height: 100%;
        }
      }
    }

    >.data {
      padding-left: 10px;
      position: relative;
      overflow: hidden;

      >.filedata {
        >dt {
          font-size: 0.7rem;
        }

        >dd {
          margin-bottom: 5px;
          overflow: hidden;
        }
      }

      >.console {
        position: absolute;
        bottom: 0;
        width: calc(100% - 10px);
      }
    }
  }
}
</style>

// apps/www/app/components/ImageUploader/index.tsx
﻿// import { Editor } from '@tiptap/react';
// import dayjs from 'dayjs';
// import { getDownloadURL, ref, uploadBytes } from 'firebase/storage';
import { FC, useState } from 'react';

// import { useStorage } from '~/hooks/firebase/useStorage';
// import { getExt } from '~/utils/file';
import { ResizedImage } from '~/utils/image';

import { DropZone } from './DropZone';
import { Preview } from './Preview';
import { containerStyle, innerStyle } from './style.css';

// import { getStorage, uploadBytes, getDownloadURL, ref as storageRef } from 'firebase/storage';
// import { useFirebase } from '~~/composables/firebase/useFirebase';

type Props = {
  // editor: Editor;
  // show: boolean;
  onClose: () => void;
  onUpload: () => void;
  isUploading: boolean;
  // onChange?: (file: string) => void;
  // defaultImage?: string;
};

export const ImageUploader: FC<Props> = ({
  isUploading = false,
  onUpload,
  onClose,
}) => {
  // const props = withDefaults(
  //   defineProps<Props>(),
  //   {
  //     onChange: () => {},
  //     defaultImage: '',
  //   }
  // );

  // const { fb } = useFirebase();
  // const { storage } = useStorage();
  const [file, setFile] = useState<ResizedImage>();
  // const [isUploading, setIsUploading] = useState(false);

  // const uploadImage = async () => {
  //   if (!editor || !file) return;
  //   console.log('file', file);

  //   const ext = getExt(file.file);
  //   if (!ext) return;

  //   try {
  //     setIsUploading(true);
  //     const now = dayjs();

  //     const filename = `posts/${now.format('YYYY/MM')}/${now.unix()}.${ext}`;
  //     console.log('filename', filename);

  //     const uploadHandler = ref(storage, filename);

  //     await uploadBytes(uploadHandler, file.file);
  //     const url = await getDownloadURL(uploadHandler);

  //     editor.chain().focus().setImage({ src: url }).run();
  //     setFile(undefined);
  //   } catch (e) {
  //     console.error(e);
  //   }

  //   onClose();
  //   setIsUploading(false);
  // };

  const onUpdateFile = (file: ResizedImage) => {
    setFile(file);
  };

  const removeImage = () => {
    setFile(undefined);
  };

  return (
    <div className={containerStyle}>
      <div className={innerStyle}>
        <Preview
          file={file}
          onRemoveImage={removeImage}
          isUploading={isUploading}
          onUpload={onUpload}
        />
        {!file?.url && <DropZone onUpdate={onUpdateFile} onClose={onClose} />}
      </div>
    </div>
  );
};
